import { createHash } from "node:crypto";
import { spawnSync } from "node:child_process";
import { chmodSync, existsSync, lstatSync, mkdirSync, readFileSync, readdirSync, realpathSync, writeFileSync } from "node:fs";
import { basename, isAbsolute, relative, resolve, sep } from "node:path";
import Database from "better-sqlite3";
import { loadAuditedRealCertificationCafs } from "./caf-real-bundle-audit";
import { runFacturaSetDryRun } from "./factura-set-dry-run";

const ORIGINAL_ENVELOPE_SHA256 = "da3875da0dd1190fe290393f063e02f31d3be583454e349387f24dff59196e37";
const STATUS_7_RESPONSE_SHA256 = "1cc59e211e5217abf6f88132a1b9c30cfba312f12bd2a8afc834d78fe31108ef";
const CORRECTION_001_ENVELOPE_SHA256 = "738197d2ab1d65c0f83d35b97408331114c5617cc6647768cb95dcfedc779ec3";
const CORRECTION_001_TRACK_FINGERPRINT = "0430bc27374b80a4";
const CORRECTION_001_CONFIRMATION = "CORRECT_SET_4959698_da3875da0dd1190fe290393f063e02f31d3be583454e349387f24dff59196e37_AFTER_STATUS_7_SCH_00001_1cc59e211e5217abf6f88132a1b9c30cfba312f12bd2a8afc834d78fe31108ef";
const CORRECTION_002_CONFIRMATION = "PREPARE_CORRECTION_002_SET_4959698_738197d2ab1d65c0f83d35b97408331114c5617cc6647768cb95dcfedc779ec3_RFR_0430bc27374b80a4_2026-07-22_DTE_TYPE_FOLIO_BASE64_76";
const CORRECTION_002_OUTPUT = "/home/verf/secure/dte-lab/set-4959698-correction-002";
const CORRECTION_002_ENVELOPE_SHA256 = "fc9a2a5836c8e93d0c6f26bf405d9ddb7db8b86b5d50d90c3ffeccc26ee62094";
const CORRECTION_002_TRACK_FINGERPRINT = "13fdc74f20f65666";
const CORRECTION_003_CONFIRMATION = "PREPARE_CORRECTION_003_SET_4959698_fc9a2a5836c8e93d0c6f26bf405d9ddb7db8b86b5d50d90c3ffeccc26ee62094_RFR_13fdc74f20f65666_2026-07-22_FINAL_CONTEXT_XMLDSIG";
const CORRECTION_003_OUTPUT = "/home/verf/secure/dte-lab/set-4959698-correction-003";
const CORRECTION_003_ENVELOPE_SHA256 = "3792002081b8f884bc0f14f3ca78ff2340fe312f7fb43dfb3f311c2cce5ae51a";
const CORRECTION_003_TRACK_FINGERPRINT = "77a28038d28ccc1e";
const CORRECTION_004_CONFIRMATION = "PREPARE_CORRECTION_004_SET_4959698_3792002081b8f884bc0f14f3ca78ff2340fe312f7fb43dfb3f311c2cce5ae51a_EPR_DTE_3_505_INHERITED_XSI";
const CORRECTION_004_OUTPUT = "/home/verf/secure/dte-lab/set-4959698-correction-004";
const HEADER = '<?xml version="1.0" encoding="ISO-8859-1"?>\n<EnvioDTE xmlns="http://www.sii.cl/SiiDte" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sii.cl/SiiDte EnvioDTE_v10.xsd" version="1.0">\n';
const FOLIOS = { "4959698-1": 1, "4959698-2": 2, "4959698-3": 3, "4959698-4": 4, "4959698-5": 1, "4959698-6": 2, "4959698-7": 3, "4959698-8": 1 } as const;

export class CorrectionPrepareError extends Error { readonly code = "CERTIFICATION_SET_CORRECTION_REJECTED"; constructor(readonly field: string) { super("Controlled correction preparation failed"); } }
const fail = (field: string): never => { throw new CorrectionPrepareError(field); };
const shaBytes = (value: Buffer | string) => createHash("sha256").update(value).digest("hex");
const shaFile = (path: string) => shaBytes(readFileSync(path));
const required = (env: NodeJS.ProcessEnv, name: string) => { const value = String(env[name] ?? "").trim(); return value || fail(name.toLowerCase()); };
type SanitizedErrorFrame = { errorFunction: string; errorFileBasename: string; errorLine: string; errorColumn: string };
function sanitizeErrorMessage(value: string): string { return value.replace(/(?:file:)?\/(?:[^\s<>"']+\/)*[^\s<>"']+/g, "[PATH]").replace(/\b\d{1,2}\.\d{3}\.\d{3}-[\dKk]\b|\b\d{7,8}-[\dKk]\b/g, "[RUT]").replace(/<\?xml[\s\S]*?\?>|<[A-Za-z_][^>]*>[\s\S]*?<\/[A-Za-z_][^>]*>|<[A-Za-z_][^>]*\/>/gi, "[XML]").replace(/(?<![A-Za-z0-9+/_=-])[A-Za-z0-9+/_=-]{32,}(?![A-Za-z0-9+/_=-])/g, "[DATA]").replace(/\b(?:token|track(?:\s*id)?)(?:\s*[:=]\s*|\s+)[^\s,;]+/gi, "[SECRET]"); }
function firstInternalErrorFrame(stack: unknown): SanitizedErrorFrame { const lines = typeof stack === "string" ? stack.split(/\r?\n/) : []; for (const line of lines) { const match = line.match(/^\s*at\s+(?:(.*?)\s+\()?((?:file:\/\/)?[^()\s]*\/(?:lib|scripts)\/dte\/[^():\s]+):(\d+):(\d+)\)?\s*/); if (match) return { errorFunction: (match[1] || "anonymous").trim(), errorFileBasename: basename(match[2]), errorLine: match[3], errorColumn: match[4] }; } return { errorFunction: "unlocated", errorFileBasename: "unlocated", errorLine: "0", errorColumn: "0" }; }
export function formatCorrectionPrepareDiagnostic(error: unknown): string { const candidate = error instanceof Error ? error : new Error(String(error)); const withCode = candidate as Error & { code?: unknown }; const frame = firstInternalErrorFrame(candidate.stack); return ["errorName=" + (candidate.name || "Error"), "errorCode=" + (typeof withCode.code === "string" ? withCode.code : "INTERNAL"), "errorFunction=" + frame.errorFunction, "errorFileBasename=" + frame.errorFileBasename, "errorLine=" + frame.errorLine, "errorColumn=" + frame.errorColumn, "sanitizedMessage=" + sanitizeErrorMessage(candidate.message || "internal error")].join("\n"); }
function external(path: string, root: string, field: string): string { if (!isAbsolute(path) || relative(resolve(root), resolve(path)).split(sep)[0] !== "..") fail(field); return resolve(path); }
function file600(path: string, root: string, field: string): string { const value = external(path, root, field); const stat = lstatSync(value); if (!stat.isFile() || stat.isSymbolicLink() || realpathSync(value) !== value || stat.uid !== process.getuid?.() || (stat.mode & 0o777) !== 0o600) fail(field); return value; }
function directory700(path: string, root: string, field: string): string { const value = external(path, root, field); const stat = lstatSync(value); if (!stat.isDirectory() || stat.isSymbolicLink() || realpathSync(value) !== value || stat.uid !== process.getuid?.() || (stat.mode & 0o777) !== 0o700) fail(field); return value; }
function ledgerReadOnly(path: string, root: string): string { const value = file600(path, root, "ledger"); const before = shaFile(value); const db = new Database(value, { readonly: true, fileMustExist: true }); try { const rows = db.prepare("SELECT type_code,folio,state,reserved_case FROM folios").all() as Array<{ type_code: number; folio: number; state: string; reserved_case: string | null }>; const issued = rows.filter((row) => row.state === "issued"); const available = rows.filter((row) => row.state === "available"); if (issued.length !== 8 || available.length !== 3 || rows.some((row) => row.state === "reserved")) fail("ledger_states"); for (const [type, folio] of [[33, 1], [33, 2], [33, 3], [33, 4], [61, 1], [61, 2], [61, 3], [56, 1]]) if (!issued.some((row) => row.type_code === type && row.folio === folio && String(row.reserved_case ?? "").startsWith("SET-4959698-ATTEMPT-001:"))) fail("ledger_issued"); for (const [type, folio] of [[33, 5], [61, 4], [56, 2]]) if (!available.some((row) => row.type_code === type && row.folio === folio)) fail("ledger_contingency"); return before; } finally { db.close(); } }
function manifestFilesValid(manifest: Record<string, unknown>, manifestPath: string, envelopePath: string, envelopeSha256: string): boolean { const files = Array.isArray(manifest.files) ? manifest.files as Array<{ file?: unknown; sha256?: unknown }> : []; const expected = ["EnvioDTE-4959698-CERTIFICATION.xml", ...Array.from({ length: 8 }, (_, index) => `4959698-${index + 1}-DTE-CERTIFICATION.xml`)]; return manifest.fixtureMode === false && files.length === 9 && basename(manifestPath) === "manifest-4959698-CERTIFICATION.json" && expected.every((name) => files.some((file) => file.file === name)) && files.some((file) => file.file === basename(envelopePath) && file.sha256 === envelopeSha256); }
function validateCorrectionOneManifest(manifest: Record<string, unknown>, manifestPath: string, envelopePath: string): void { if (!manifestFilesValid(manifest, manifestPath, envelopePath, CORRECTION_001_ENVELOPE_SHA256) || manifest.envelopeSha256 !== CORRECTION_001_ENVELOPE_SHA256 || manifest.correctionOfEnvelopeSha256 !== ORIGINAL_ENVELOPE_SHA256 || manifest.correctionReason !== "STATUS_7_SCH_00001" || manifest.correctionResponseSha256 !== STATUS_7_RESPONSE_SHA256) fail("old_manifest"); }
function validateSubmittedCorrectionRecord(recordPath: string, root: string, envelopeSha256: string, trackFingerprint: string): string { const value = file600(recordPath, root, "old_registry"); const bytes = readFileSync(value); let record: Record<string, unknown> = {}; try { record = JSON.parse(bytes.toString("utf8")); } catch { fail("old_registry"); } const trackId = typeof record.trackId === "string" ? record.trackId : ""; if (record.envelopeSha256 !== envelopeSha256 || !((record.state === "submitted") || (record.submitted === true && record.stage === "submitted")) || !trackId || shaBytes(trackId).slice(0, 16) !== trackFingerprint) fail("old_registry"); return shaBytes(bytes); }
function validateSubmittedCorrectionOneRecord(recordPath: string, root: string): string { return validateSubmittedCorrectionRecord(recordPath, root, CORRECTION_001_ENVELOPE_SHA256, CORRECTION_001_TRACK_FINGERPRINT); }
function validateCorrectionTwoManifest(manifest: Record<string, unknown>, manifestPath: string, envelopePath: string): void { if (!manifestFilesValid(manifest, manifestPath, envelopePath, CORRECTION_002_ENVELOPE_SHA256) || manifest.envelopeSha256 !== CORRECTION_002_ENVELOPE_SHA256 || manifest.correctionNumber !== 2 || manifest.correctionOfEnvelopeSha256 !== CORRECTION_001_ENVELOPE_SHA256 || manifest.correctionOfTrackIdFingerprint !== CORRECTION_001_TRACK_FINGERPRINT || manifest.correctionOfStatus !== "RFR" || manifest.correctionReason !== "RFR_WRONG_DTE_ASSOCIATION_AND_BASE64_LINE_LENGTH") fail("old_manifest"); }
function maxBase64LineLength(xml: string): number { let max = 0; for (const match of xml.matchAll(/<(FRMT|SignatureValue|X509Certificate)(?:\s[^>]*)?>([\s\S]*?)<\/\1>/g)) for (const line of match[2].split("\n")) max = Math.max(max, line.length); return max; }
function xmlsecPersistedGate(envelopePath: string, certificatePath: string): boolean { const xml = readFileSync(envelopePath, "latin1"); const ids = [...xml.matchAll(/<Documento\b[^>]*\bID="([^"]+)"/g)].map((match) => match[1]); const setId = xml.match(/<SetDTE\b[^>]*\bID="([^"]+)"/)?.[1] ?? ""; const verify = (id: string) => spawnSync("xmlsec1", ["--verify", "--id-attr:ID", "Documento", "--id-attr:ID", "SetDTE", "--pubkey-cert-pem", certificatePath, "--node-xpath", `//*[local-name()='Signature'][.//*[local-name()='Reference' and @URI='#${id}']]`, envelopePath], { stdio: "ignore" }).status === 0; return ids.length === 8 && ids.every(verify) && Boolean(setId) && verify(setId); }

export function prepareFacturaCertificationSetCorrection(env: NodeJS.ProcessEnv = process.env, repoRoot = process.cwd()) {
  if (env.DTE_MODE !== "certification" || env.DTE_SII_ENV !== "certification" || env.NODE_ENV === "production") fail("environment");
  if (env.DTE_SII_LIVE_AUTH === "true" || env.DTE_SII_ENABLE_SUBMIT === "true" || env.DTE_SII_ENABLE_STATUS === "true" || env.DTE_SII_TOKEN || env.DTE_TRACK_ID) fail("external_operations");
  const correctionNumber = String(env.DTE_FACTURA_CERTIFICATION_CORRECTION_NUMBER ?? "1");
  if (correctionNumber !== "1" && correctionNumber !== "2" && correctionNumber !== "3" && correctionNumber !== "4") fail("correction_number");
  const correctionTwo = correctionNumber === "2";
  const correctionThree = correctionNumber === "3";
  const correctionFour = correctionNumber === "4";
  const oldEnvelopeSha256 = correctionFour ? CORRECTION_003_ENVELOPE_SHA256 : correctionThree ? CORRECTION_002_ENVELOPE_SHA256 : correctionTwo ? CORRECTION_001_ENVELOPE_SHA256 : ORIGINAL_ENVELOPE_SHA256;
  if (required(env, "DTE_FACTURA_CERTIFICATION_CORRECTION_CONFIRM") !== (correctionFour ? CORRECTION_004_CONFIRMATION : correctionThree ? CORRECTION_003_CONFIRMATION : correctionTwo ? CORRECTION_002_CONFIRMATION : CORRECTION_001_CONFIRMATION)) fail("confirmation");
  if (required(env, "DTE_FACTURA_CERTIFICATION_CORRECTION_OLD_ENVELOPE_SHA256") !== oldEnvelopeSha256) fail("evidence_hash");
  if (!correctionTwo && !correctionThree && !correctionFour && required(env, "DTE_FACTURA_CERTIFICATION_CORRECTION_RESPONSE_SHA256") !== STATUS_7_RESPONSE_SHA256) fail("evidence_hash");
  const oldEnvelope = file600(required(env, "DTE_FACTURA_CERTIFICATION_CORRECTION_OLD_ENVELOPE_PATH"), repoRoot, "old_envelope");
  const oldManifest = file600(required(env, "DTE_FACTURA_CERTIFICATION_CORRECTION_OLD_MANIFEST_PATH"), repoRoot, "old_manifest");
  if (shaFile(oldEnvelope) !== oldEnvelopeSha256) fail("old_envelope_hash");
  let previousManifest: Record<string, unknown> = {}; try { previousManifest = JSON.parse(readFileSync(oldManifest, "utf8")); } catch { fail("old_manifest"); }
  let correctionOfManifestSha256: string | undefined; let correctionOfRegistrySha256: string | undefined;
  if (correctionFour) { correctionOfManifestSha256 = shaFile(oldManifest); correctionOfRegistrySha256 = validateSubmittedCorrectionRecord(required(env, "DTE_FACTURA_CERTIFICATION_CORRECTION_OLD_REGISTRY_PATH"), repoRoot, CORRECTION_003_ENVELOPE_SHA256, CORRECTION_003_TRACK_FINGERPRINT); } else if (correctionThree) { validateCorrectionTwoManifest(previousManifest, oldManifest, oldEnvelope); correctionOfManifestSha256 = shaFile(oldManifest); correctionOfRegistrySha256 = validateSubmittedCorrectionRecord(required(env, "DTE_FACTURA_CERTIFICATION_CORRECTION_OLD_REGISTRY_PATH"), repoRoot, "fc9a2a5836c8e93d0c6f26bf405d9ddb7db8b86b5d50d90c3ffeccc26ee62094", CORRECTION_002_TRACK_FINGERPRINT); } else if (correctionTwo) { validateCorrectionOneManifest(previousManifest, oldManifest, oldEnvelope); correctionOfManifestSha256 = shaFile(oldManifest); correctionOfRegistrySha256 = validateSubmittedCorrectionOneRecord(required(env, "DTE_FACTURA_CERTIFICATION_CORRECTION_OLD_REGISTRY_PATH"), repoRoot); } else if (!manifestFilesValid(previousManifest, oldManifest, oldEnvelope, ORIGINAL_ENVELOPE_SHA256)) fail("old_manifest");
  const ledger = file600(required(env, "DTE_FACTURA_CERTIFICATION_CORRECTION_LEDGER_PATH"), repoRoot, "ledger"); const ledgerHash = ledgerReadOnly(ledger, repoRoot);
  const output = external(required(env, "DTE_FACTURA_CERTIFICATION_CORRECTION_OUTPUT_DIR"), repoRoot, "output"); if ((correctionTwo && output !== CORRECTION_002_OUTPUT) || (correctionThree && output !== CORRECTION_003_OUTPUT) || (correctionFour && output !== CORRECTION_004_OUTPUT) || existsSync(output)) fail("output_exists");
  const registryDir = (correctionTwo || correctionFour) ? directory700(required(env, "DTE_FACTURA_CERTIFICATION_SUBMIT_REGISTRY_DIR"), repoRoot, "registry") : undefined;
  const certificate = file600(required(env, "DTE_CERT_PATH"), repoRoot, "certificate"); const privateKey = file600(required(env, "DTE_PRIVATE_KEY_PATH"), repoRoot, "private_key");
  const audited = loadAuditedRealCertificationCafs(env, repoRoot); const importedCafByType = Object.fromEntries(audited.cafs.map((caf) => [caf.typeCode, { cafXml: caf.cafXml, privateKeyPem: caf.privateKeyPem, publicKeyPem: caf.publicKeyPem }]));
  mkdirSync(output, { mode: 0o700 }); chmodSync(output, 0o700); writeFileSync(resolve(output, "correction-state.json"), JSON.stringify({ state: "partial" }), { flag: "wx", mode: 0o600 });
  try {
    const result = runFacturaSetDryRun({ env, repoRoot, outputDir: output, realCertification: { certificatePath: certificate, privateKeyPath: privateKey }, overrides: { folioByCase: FOLIOS, importedCafByType } });
    const envelope = resolve(output, "EnvioDTE-4959698-CERTIFICATION.xml"); const manifestPath = resolve(output, "manifest-4959698-CERTIFICATION.json"); const bytes = readFileSync(envelope); const xml = bytes.toString("latin1"); const envelopeSha256 = shaFile(envelope);
    if (!xml.startsWith(HEADER) || bytes.subarray(0, 3).equals(Buffer.from([0xef, 0xbb, 0xbf])) || !Buffer.from(xml, "latin1").equals(bytes) || envelopeSha256 === oldEnvelopeSha256 || !xmlsecPersistedGate(envelope, certificate) || result.dteXsd !== "8/8" || result.envioDteXsd !== "valid" || result.tedFrmt !== "8/8" || result.dteSignatures !== "8/8" || result.envelopeSignature !== "valid" || result.references !== "valid" || result.totals !== "valid" || maxBase64LineLength(xml) > 76 || shaFile(ledger) !== ledgerHash) fail("final_validation");
    if ((correctionTwo || correctionFour) && existsSync(resolve(String(registryDir), `${envelopeSha256}.json`))) fail("registry_exists");
    const manifest = JSON.parse(readFileSync(manifestPath, "utf8")) as Record<string, unknown>;
    Object.assign(manifest, correctionFour ? { correctionNumber: 4, correctionOfEnvelopeSha256: CORRECTION_003_ENVELOPE_SHA256, correctionOfManifestSha256, correctionOfRegistrySha256, correctionOfTrackIdFingerprint: CORRECTION_003_TRACK_FINGERPRINT, correctionOfStatus: "EPR", correctionReason: "DTE_3_505_INHERITED_XSI_NAMESPACE", portalObservedDate: "2026-07-22", documentsMatched: "8/8" } : correctionThree ? { correctionNumber: 3, correctionOfEnvelopeSha256: CORRECTION_002_ENVELOPE_SHA256, correctionOfManifestSha256, correctionOfRegistrySha256, correctionOfTrackIdFingerprint: CORRECTION_002_TRACK_FINGERPRINT, correctionOfStatus: "RFR", correctionReason: "RFR_DETACHED_C14N_DIGEST_MISMATCH", portalObservedDate: "2026-07-22" } : correctionTwo ? { correctionNumber: 2, correctionOfEnvelopeSha256: CORRECTION_001_ENVELOPE_SHA256, correctionOfManifestSha256, correctionOfRegistrySha256, correctionOfTrackIdFingerprint: CORRECTION_001_TRACK_FINGERPRINT, correctionOfStatus: "RFR", statusEvidenceSource: "human_portal_observation", portalObservedStatus: "RECHAZADO_POR_ERROR_EN_FIRMA", portalObservedDate: "2026-07-22", correctionReason: "RFR_WRONG_DTE_ASSOCIATION_AND_BASE64_LINE_LENGTH", associationKey: "dteType:folio", documentsMatched: "8/8" } : { correctionOfEnvelopeSha256: ORIGINAL_ENVELOPE_SHA256, correctionReason: "STATUS_7_SCH_00001", correctionResponseSha256: STATUS_7_RESPONSE_SHA256 }, { sourceCommit: "6c2ffae", envelopeSha256, folios: { "33": [1, 2, 3, 4], "61": [1, 2, 3], "56": [1] }, ledgerUnchanged: true });
    writeFileSync(manifestPath, JSON.stringify(manifest, null, 2), { mode: 0o600 }); chmodSync(manifestPath, 0o600); writeFileSync(resolve(output, "correction-state.json"), JSON.stringify({ state: "ready", ledgerUnchanged: true }), { mode: 0o600 }); if (!readdirSync(output).every((name) => (lstatSync(resolve(output, name)).mode & 0o777) === 0o600)) fail("output_permissions");
    return { status: "CORRECTION_PREPARED_OFFLINE" as const, documents: 8, type33: 4, type61: 3, type56: 1, folios: "33:1-4,61:1-3,56:1", ledgerUnchanged: true, envelopeSha256, siiContacted: false, readyForSubmitPreflight: true };
  } catch (error) { writeFileSync(resolve(output, "correction-state.json"), JSON.stringify({ state: "partial" }), { mode: 0o600 }); if (error instanceof CorrectionPrepareError) throw error; throw new CorrectionPrepareError("generation"); }
}
export const formatCorrectionPrepare = (result: ReturnType<typeof prepareFacturaCertificationSetCorrection>) => Object.entries(result).map(([key, value]) => `${key}=${value}`).join("\n");
export const formatCorrectionPrepareError = (error: unknown) => { const safe = error instanceof CorrectionPrepareError ? error : new CorrectionPrepareError("internal"); return `code=${safe.code}\nfield=${safe.field}\nmessage=controlled_operation_failed`; };
